# Namespace
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: devops-phase2
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-k8s-phase2-deployment
#  namespace: devops-phase2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-k8s-phase2
  template:
    metadata:
      labels:
        app: devops-k8s-phase2
    spec:
      containers:
      - name: devops-k8s-phase2
        image: 19820401/devops-k8s-phase2:1.0.5
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 5008
        env:
        - name: HELLO_FROM_CONFIGMAP
          valueFrom:
            configMapKeyRef:
              name: devops-k8s-phase2-configmap
              key: hello_from_configmap 
        - name: GREETINGS_IN_THE_BODY
          valueFrom:
            configMapKeyRef:
              name: devops-k8s-phase2-configmap
              key: greetings_in_the_body
        volumeMounts:
        - name: health-volume
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: 5008
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5008
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
      volumes:
      - name: health-volume
        persistentVolumeClaim:
          claimName: health-check-pvc

---
# Service 
apiVersion: v1
kind: Service
metadata:
  name: devops-k8s-phase2-service
#  namespace: devops-phase2
spec:
  selector:
    app: devops-k8s-phase2
  type: NodePort
  ports:
    - protocol: TCP
      port: 5008        # Service port
      targetPort: 5008  # Container port
      nodePort: 30008   # External port 

---
# HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-k8s-phase2-service
#  namespace: devops-phase2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-k8s-phase2
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50