# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: devops-phase2
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-k8s-phase2-deployment
  namespace: devops-phase2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-k8s-phase2
  template:
    metadata:
      labels:
        app: devops-k8s-phase2
    spec:
      containers:
      - name: devops-k8s-phase2
        image: 19820401/devops-k8s-phase2:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5008  
---
# Service 
kind: Service
metadata:
  name: devops-k8s-phase2-service
  namespace: devops-phase2
spec:
  selector:
    app: devops-k8s-phase2
  type: NodePort
  ports:
    - protocol: TCP
      port: 5008        # Service port
      targetPort: 5008  # Container port
      nodePort: 30008   # External port 

---
# HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-k8s-phase2-service
  namespace: devops-phase2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-k8s-phase2
  minReplicas: 1
  maxReplicas: 10
  #targetCPUUtilizationPercentage: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50