# Namespace
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: devops-phase2
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-k8s-phase2-deployment
#  namespace: devops-phase2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-k8s-phase2
  template:
    metadata:
      labels:
        app: devops-k8s-phase2
    spec:
      containers:
      - name: devops-k8s-phase2
        image: 19820401/devops-k8s-phase2:2.0.0
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 5008

        env:
        - name: HELLO_FROM_CONFIGMAP
          valueFrom:
            configMapKeyRef:
              name: devops-k8s-phase2-configmap
              key: hello_from_configmap 
        - name: GREETINGS_IN_THE_BODY
          valueFrom:
            configMapKeyRef:
              name: devops-k8s-phase2-configmap
              key: greetings_in_the_body
        volumeMounts:
        - name: health-volume
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /health
            port: 5008
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5008
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
      volumes:
      - name: health-volume
        persistentVolumeClaim:
          claimName: health-check-pvc

