version: '3.9'

services:
  devops-k8s-phase2:
    build:
      context: .
      dockerfile: Dockerfile
    image: 19820401/devops-k8s-phase2:1.0.2
    container_name: devops-k8s-phase2
    ports:
      - "5008:5008"
    volumes:
      - devops_k8s_phase2_volume:/app/static
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  devops_k8s_phase2_volume: {}
